#!/bin/bash

# Retrieve arguments
domain=$1
path=$2

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a caldavzap
if [[ ! $? -eq 0 ]]; then
    exit 1
fi

# TODO : check that radicale is installed

# --- copy files ---
final_path=/var/www/caldavzap
sudo mkdir -p $final_path
sudo cp -r ../sources/* $final_path

# --- config.js ---
sed -i "s@YNH_DOMAIN@$domain@g" ../conf/config.js
sed -i "s@YNH_WWW_PATH@$path@g" ../conf/config.js
# TODO
# langage=$(sudo bash -c "echo $LANG | cut -d '.' -f 1")
# sed -i "s@YNH_INTERFACE_LANGUAGE@$langage@g" ../conf/config.js
# TODO
# timezone=$(cat /etc/timezone)
# sed -i "s@YNH_TIMEZONE@$timezone@g" ../conf/config.js
cp ../conf/config.js $final_path

# --- config.inc ---
sed -i "s@YNH_DOMAIN@$domain@g" ../conf/config.inc
radicale_path=$(sudo yunohost app setting radicale path)
radicale_path=${radicale_path%/}
sed -i "s@YNH_RADICALE_PATH@$radicale_path@g" ../conf/config.inc
cp ../conf/config.inc $final_path/auth

# --- nginx.conf ---
sed -i "s@YNH_WWW_PATH@$path@g" ../conf/nginx.conf
sed -i "s@YNH_WWW_ALIAS@$final_path/@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/caldavzap.conf

# --- Permissions ---
sudo find $final_path -type f | xargs sudo chmod 644
sudo find $final_path -type d | xargs sudo chmod 755
sudo chown -R root: $final_path

sudo service nginx reload
sudo yunohost app ssowatconf
