#!/bin/bash

domain=$(sudo yunohost app setting caldavzap domain)
path=$(sudo yunohost app setting caldavzap path)

# Remove trailing "/" for next commands
path=${path%/}

# Copy files to the right place
final_path=/var/www/caldavzap
sudo mkdir -p $final_path
sudo cp -a ../sources/* $final_path

# Files owned by root, www-data can just read
sudo find $final_path -type f | xargs sudo chmod 644
sudo find $final_path -type d | xargs sudo chmod 755
sudo chown -R root: $final_path

# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@YNH_WWW_PATH@$path@g" ../conf/nginx.conf
sed -i "s@YNH_WWW_ALIAS@$final_path/@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/caldavzap.conf

sudo service nginx reload
sudo yunohost app ssowatconf
